<?php if (! defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED !== true) {die();}

$aMenuLinks = [
    [
        'Легковые',
        '/catalog/cars/',
        [],
        [],
        ''
    ],
    [
        'Внедорожники',
        '/catalog/off-road/',
        [],
        [],
        ''
    ],
    [
        'Раритетные',
        '/catalog/rarity/',
        [],
        [],
        ''
    ],
    [
        'Распродажа',
        '/catalog/sale/',
        [],
        [],
        ''
    ],
    [
        'Новинки',
        '/catalog/new/',
        [],
        [],
        ''
    ],
];
